services:
  api_v2:
    build:
      context: ./services/api-v2
    env_file:
      - ./api-v2.env
    depends_on:
      - postgres
      - redis
    networks:
      - private
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  nginx:
    networks:
      - public
      - private
    # מפות Statics: השם api_v2 -> ה-IP הנוכחי (עד שנחזיר DNS פנימי)
    extra_hosts:
      - "api_v2:172.19.0.7"
    # מיפוי קונפיג מההוסט לתוך הקונטיינר (קריאה בלבד)
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx/snippets:/etc/nginx/snippets:ro
      - ./conf/nginx/includes:/etc/nginx/includes:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/includes:/etc/nginx/includes:ro
