FROM node:20-bullseye AS build
WORKDIR /app
COPY services/api-v2/package.json ./package.json
RUN npm install
COPY prisma ./prisma
RUN npx prisma generate
COPY services/api-v2/tsconfig.json ./tsconfig.json
COPY services/api-v2/src ./src
RUN npm run build
RUN npm prune --omit=dev
FROM node:20-bullseye
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
EXPOSE 3000
CMD ["node","dist/index.js"]
