# Added by sec-861-nginx-headers-bindmount-v1 — mounts security headers into nginx container
services:
  nginx:
    volumes:
      - '/root/backgammon-mini-app/docs/sec/snippets/nginx-sec-headers.stage8.conf:/etc/nginx/conf.d/zz-duelly-sec8-headers.conf:ro'
